### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/3RScan/points/000.bin'

### ISSUE THREAD

**Issue by wtang126** [xuxw98/ESAM#10]
Thank you very much for the excellent online method. However，an error occurred when I was evaluating the 3RScan-mv dataset using the ESAM-E model, and I executed the following command:

CUDA_VISIBLE_DEVICES=3 PYTHONPATH=./ python tools/test.py configs/ESAM-E_CA/ESAM-E_online_3rscan_CA_test.py model-esam/ESAM-E_CA_online_epoch_128.pth --work-dir ./ESAM-E_online_3rscan_CA_test/

I processed the data set as follows and followed the guidance(I have downloaded the data set and renamed it to ['000', '001',..., '045']):
1、python load_3rscan_mv_data_fast.py
2、mv 3RScan-mv 3RScan-mv_fast
3、python tools/create_data.py 3rscan_mv --root-path ./data/3RScan-mv_fast --out-dir ./data/3RScan-mv_fast --extra-tag 3rscan_mv

**Comment by XXXCARREY** [comment]
Thank you for your interest. The missing file is the scene reconstructed point cloud file. Our model evaluation requires the reconstructed dataset, specifically the `3RScan` dataset mentioned in the `Dataset Preparation` readme. Please complete the processing of the reconstructed dataset first, and then proceed with the performance evaluation.

**Comment by wtang126** [comment]
Understood, thank you for your reply!
