### ISSUE TITLE
In the README.md of ScanNet-MV and scenenn, the download address of 2D data and SceneNN data are both invalid.

### ISSUE THREAD

**Issue by spatiall** [xuxw98/ESAM#11]
Thanks to the author for your work. In the process of preparing the data, I found that in the README.md of ScanNet-MV and scenenn, the download address of 2D data and SceneNN data are both invalid.How should I solve this problem?
![2024-09-19 17-50-37 的屏幕截图](https://github.com/user-attachments/assets/7225010d-7e8a-45b7-a63f-14c47094a543)

**Comment by xuxw98** [comment]
Hi,
Thanks for your interest! The previous cloud disk account has expired, we will complete the update as soon as possible

**Comment by xuxw98** [comment]
We have repair the cloud disk. You can have a try now!
