### ISSUE TITLE
for scannet200-mv,the reproducible results are inconsistent

### ISSUE THREAD

**Issue by spatiall** [xuxw98/ESAM#19]
Hello author, after training and getting the corresponding weight of scannet200-mv, I tested and found that the AP obtained was about ten percent lower than that mentioned in the paper. But I didn't modify the configuration file, and I got the same result as you after using the weights you provided, which may mean that the dataset and the processing of it is fine. Is there any other possible reason?
![scannet200-mv](https://github.com/user-attachments/assets/d12e0c74-26bb-491e-8bab-8138a555496c)

**Comment by xuxw98** [comment]
Hi,
Have you first trained SV model on scannet200-SV and then used its checkpoint as an initialization for scannet200-MV?

**Comment by xuxw98** [comment]
Hi,
Have you first trained SV model on scannet200-SV and then used its checkpoint as an initialization for scannet200-MV?

**Comment by spatiall** [comment]
yes, I did it. Here are the test results of my ScanNet200-SV
![scannet200-sv](https://github.com/user-attachments/assets/abb37415-7b86-4474-b87c-7308f7fb49a8)

**Comment by spatiall** [comment]
This is the code in the configuration file, and I didn't change it
![load_from](https://github.com/user-attachments/assets/2d8c61c8-e4fb-4ece-9096-cd99f0411f37)
Or I need to do something else to use scannet200-SV's checkpoint as an initialization for scannet200-MV?

**Comment by XXXCARREY** [comment]
Hello! The test results of your SV model on `ScanNet200-SV` match the results we obtained, indicating that there is no issue with the SV model training. Could you share the full training log of the MV model with us? We’d like to check if there are any problems in it.

**Comment by xuxw98** [comment]
We have re-trained our model and got correct results. We are sorry that we do not find any mistake or error in your training log. Considering the fact that there is no problem in your SV model and Online validation dataset, we recommend to check your Online training set. Maybe you can re-generate it and train again. Best wishes~

**Comment by spatiall** [comment]
ok,thanks.I wil try it.
