### ISSUE TITLE
vis question

### ISSUE THREAD

**Issue by GeLuzhou** [xuxw98/ESAM#25]
When I use 3Rscan dataset, how should I fill  --scene_idx  in.
`CUDA_VISIBLE_DEVICES=0 python vis_demo/online_demo.py --scene_idx scene000  --config /home/coastz/codes/
ESAM/configs/ESAM-E_CA/ESAM-E_online_3rscan_CA_test.py --checkpoint /home/coastz/codes/ESAM/checkpoint/ESAM-E_CA_online_epoch_128.pth
usage: online_demo.py [-h] [--scene-idx SCENE_IDX] [--config CONFIG] [--checkpoint CHECKPOINT] [--device DEVICE] [--use_vis USE_VIS]
online_demo.py: error: unrecognized arguments: --scene_idx scene000`

**Comment by GeLuzhou** [comment]
After I used the modified demo, the following problems occurred. I added them to my sys.path and still got errors.

 File "/home/coastz/codes/ESAM/oneformer3d/img_backbone.py", line 3, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 466, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import oneformer3d
  File "/home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 478, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['oneformer3d']}, the current sys.path is: 
    /home/coastz/codes/ESAM/vis_demo
    /home/coastz/anaconda3/envs/ESAM/lib/python38.zip
    /home/coastz/anaconda3/envs/ESAM/lib/python3.8
    /home/coastz/anaconda3/envs/ESAM/lib/python3.8/lib-dynload
    /home/coastz/.local/lib/python3.8/site-packages
    /home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages
    /home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages/pointops-1.0-py3.8-linux-x86_64.egg
    /home/coastz/codes/ESAM
    /home/coastz/codes/ESAM/oneformer3d
    /home/coastz/codes/ESAM/FastSAM/ultralytics
    /tmp/tmp0gjvy9do
    /home/coastz/anaconda3/envs/ESAM/lib/python3.8/site-packages/MinkowskiEngine
    /home/coastz/codes/ESAM/FastSAM/ultralytics

**Comment by XXXCARREY** [comment]
"It seems that this is because you haven't installed the `ultralytics` library. You can try running `pip install ultralytics==8.0.120`."
