### ISSUE TITLE
Evaluate code requests and questions about parallel computing

### ISSUE THREAD

**Issue by Xin200203** [xuxw98/ESAM#26]
Very inspiring work. Could you please make your accuracy evaluation code public? I hope to be able to reproduce your experiments to learn better. By the way, your part about parallel computing is very eye-opening to me, but I don't fully understand it. I wonder if you can point this out to me with the code. Thank you very much!

**Comment by xuxw98** [comment]
The evaluation code is already released. You can refer to [here](https://github.com/xuxw98/ESAM/blob/main/docs/run.md) for training and evaluation.

For parallel computing, I guess you mean our mask merging strategy. We convert mask merging to token merging for efficient computing. You can refer to [here](https://github.com/xuxw98/ESAM/blob/main/oneformer3d/instance_merge.py#L208) for more details.
