### ISSUE TITLE
evalutae index

### ISSUE THREAD

**Issue by linxiaoyiyi** [xuxw98/ESAM#27]
After training and getting the corresponding weight of scannet200-mv, I tested and found that the AP obtained was about five percent higher than that mentioned in the paper. The difference of my experiments is that I just train 121epoches to produce the checkpoint scannet200-sv, have you update the AP?

![O~D3LK{(~{VX7${5AAE1AHB](https://github.com/user-attachments/assets/2fdb3299-f2ae-4d97-b5bf-c937e4838daa)

**Comment by xuxw98** [comment]
Yes. Current version of ESAM has been updated and the performance is higher than that reported in our paper. We have not updated our paper yet.
