### ISSUE TITLE
About the processed SceneNN data from the repo of Online3D

### ISSUE THREAD

**Issue by xiatiandefeng666** [xuxw98/ESAM#29]
Thank you very much for your excellent open-source work! I have a question I would like to consult you about. In your outstanding work, you provided the SceneNN dataset for direct download via https://cloud.tsinghua.edu.cn/d/dab5f9ea7f0c42f38364/, which can be further used to generate SceneNN-MV. 
In the downloaded dataset, each scene contains `.npy` files corresponding to the number of images, including "ins," "label," "point," and "pose." May I ask whether these `.npy` files were generated following the process described in the official SceneNN repository (https://github.com/hkust-vgd/scenenn)? Since the steps in the official SceneNN repository are unclear, I will try to understand and replicate the process if that is the case. If not, could you provide links or papers on the data processing method for the dataset provided at https://cloud.tsinghua.edu.cn/d/dab5f9ea7f0c42f38364/?
Thank you!

**Comment by xiatiandefeng666** [comment]
Thank you very much for your previous work on Online3D. Using your provided link, we successfully generated `point.npy`, `label.npy`, and `pose.npy`. However, it seems that we are unable to generate `ins.npy`. We are interested in following your ESAM approach for some instance segmentation research. Could you please let us know if there is a way to generate `ins.npy` in a similar manner to the `point/label/pose` npy files from your link? Once again, thank you!

**Comment by xuxw98** [comment]
I do not remember how to generate ins.npy. But in our code, we only require depth/image/pose/ply/xml. It's OK to ignore ins.npy.

**Comment by xiatiandefeng666** [comment]
You meaning that ESAM in SceneNN can also perform instance segmentation relying only on pose.npy, label.npy, and point.npy, without the need for ins.npy?

**Comment by xuxw98** [comment]
yes. Actually label.npy is also unnecessary

**Comment by xuxw98** [comment]
We only use SceneNN for evaluation, not training. For evaluation, ESAM can rely solely on depth/image/pose/ply/xml and the data generated from them, without requiring dependency on label.npy and ins.npy.
