### ISSUE TITLE
When I run tools/create_data.py to generate the scannet-sv dataset, I encounter some problems~

### ISSUE THREAD

**Issue by RobinLiuZX** [xuxw98/ESAM#3]
When I run `tools/create_data.py`, the problem I encounter is: some files cannot be found, such as `scene0358_00_800_vert.npy`. When I debug, I find that the values ​​in the corresponding pose files are all **nan**, and the corresponding vert files cannot be obtained. At the same time, some files in `data/scannet-sv/meta_data/scannetv2_sv_train.txt` do not have corresponding files in the 2D dataset I downloaded, such as `scene0358_00_1600` and `scene0358_00_2000`. I want to know whether the dataset file I downloaded from kaggle is incomplete, or some file names in `scannetv2_sv_train.txt` can be omitted? I am very interested in your work and look forward to your answer. It would be a great honor!

**Comment by XXXCARREY** [comment]
Thank you for your interest! It seems that the dataset you downloaded might be incomplete. You can refer to **step 1** in the [README of Online3D](https://github.com/xuxw98/Online3D/tree/main/data/scannet-sv) to either download the processed 2D data directly or generate 2D data from the raw data.

**Comment by RobinLiuZX** [comment]
Dear authors, hello, thank you for your enthusiastic reply! When I run the `tools/train.py` file, I find that the `work_dirs/tmp/mask3d_scannet200.pth` in the corresponding config file is missing. I don't know how to get or generate this file. Could you please tell me?

**Comment by XXXCARREY** [comment]
Thank you for pointing out this issue. We followed [Oneformer3D](https://github.com/filaPro/oneformer3d) to initialize the model's backbone from [Mask3D](https://github.com/JonasSchult/Mask3D) checkpoint. You can download `mask3d_scannet200.pth` from [HERE](https://github.com/oneformer3d/oneformer3d/releases/download/v1.0/mask3d_scannet200.pth)，and put it to `work_dirs/tmp`.

**Comment by RobinLiuZX** [comment]
Thank you for your helpful help and reminder! Now I have successfully run `tools/train.py `on the scannet-sv dataset, using the ESAM-E model architecture. Thank you very much for your open source work!

**Comment by xuxw98** [comment]
Feel free to contact us if you have any further questions.
