### ISSUE TITLE
Open-Vocabulary 3D instance segmentation results on ScanNet200 dataset

### ISSUE THREAD

**Issue by Cherryreg** [xuxw98/ESAM#32]
Hi, thank you for opening your great work!
I attempted to reproduce the experiment following the experimental setup described in the paper. However, the results I obtained were rather unsatisfactory. I suspect that the issue lies in the sparsity of the 2D data utilized for calculating mask features when employing OpenMask3D. Specifically, the 2D data in question is sourced from ESAM, with a frame interval of 20 frames, which might be too sparse to yield accurate results.
Would it be possible for the author to kindly provide the specific script and detailed information regarding the Open-Vocabulary 3D instance segmentation experiment? This would greatly assist in further investigations and potential improvements.
Thank you!

**Comment by XXXCARREY** [comment]
As we mentioned in the [README](https://github.com/xuxw98/ESAM/blob/main/docs/run.md#open-vocabulary-3d-instance-segmentation), our experiments on open-vocabulary 3D instance segmentation follow the approach of [SAI3D](https://github.com/yd-yin/SAI3D?tab=readme-ov-file#assign-semantic-with-openmask3d-and-conduct-3d-instance-segmentation-evaluation), with the only difference being that we replace the class-agnostic instance masks predicted by SAI3D with the masks obtained from our model (ESAM). Through this experiment, we aim to demonstrate that our model can provide more accurate class-agnostic instance masks, which can be directly utilized by other Open-Vocabulary methods to achieve better performance. We hope our answer is helpful to you!
