### ISSUE TITLE
After I prepared the scannet200 dataset according to the process, some problems occurred during runtime

### ISSUE THREAD

**Issue by RobinLiuZX** [xuxw98/ESAM#5]
Since you did not provide the config.py files for the two initial datasets of `scannet` and `scannet200` in the open source code, I tried to refer to the config files of `scannet200` and `scannet200-sv` in `oneformer3d` and `ESAM`, but when running the `train.py` file, the following error was reported. At the same time, I found that the data in the `scannet200` folder I got was missing the `seg_info` folder and the `npy` files under it. Could you help me solve this problem?
![image](https://github.com/user-attachments/assets/bf1ced62-50af-4e74-94ee-c0d38760c20e)

**Comment by XXXCARREY** [comment]
Our model is an online model that takes RGB-D video frame sequences as input, while the two initial datasets, `scannet` and `scannet200`, contain reconstructed point cloud data suitable for offline models like Oneformer3D. In our approach, these two initial reconstructed datasets are only used for calculating segmentation metrics. Additionally, we did not use the `seg_info` folder and the files under it; thank you for pointing this out. We will update the README of `scannet` and `scannet200` to clarify our dataset processing.

**Comment by xuxw98** [comment]
This repo does not contain the code for offline perception. You can refer to [OneFormer3D ](https://github.com/filapro/oneformer3d)for training offline models.
