### ISSUE TITLE
the pointops import in load_scannet_sv_data_v2_fast.py not found

### ISSUE THREAD

**Issue by RongkunYang** [xuxw98/ESAM#6]
Hello, dear authors, may I ask which of the pointops library do you use, could you please share it, thank you.

**Comment by xuxw98** [comment]
We use the pointops used in [SAM3D](https://github.com/Pointcept/SegmentAnything3D). You can install it following SAM3D's README.

**Comment by xuxw98** [comment]
Thank you for pointing out this error. We will fix our readme on installation~

**Comment by RongkunYang** [comment]
OK, I got it, thank you.
