### ISSUE TITLE
What does the MV and SV mean in the training and testing process?

### ISSUE THREAD

**Issue by RongkunYang** [xuxw98/ESAM#7]

**Comment by xuxw98** [comment]
SV means single-view. SV models are trained on independent RGB-D frames. MV means multi-view. MV (or Online) models are trained on RGB-D sequence for online perception.

To train an online perception model, we first train it on SV data. Then we insert memory-based adapters into the model and finetune it on MV data. The auxiliary tasks, such as bounding box prediction and query contrast, are only included in the second training stage.

You can refer to our previous paper for a more detailed discussion. [Online3D,CVPR24](https://arxiv.org/pdf/2403.06974)

**Comment by RongkunYang** [comment]
OK, thank you for your enthusiastic response. I will dive into this wonderful work.
Best wishes!
